# Generated by Django 3.2 on 2021-05-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210502_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article_tags', to='article.ArticleTag', verbose_name='تگ ها / برچسب ها'),
        ),
    ]
