# Generated by Django 3.2 on 2021-05-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='article_hits', to='article.IPAddress', verbose_name='بازید'),
        ),
    ]
