# Generated by Django 3.2 on 2021-05-05 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_article_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(related_name='save_article', to='article.Article', verbose_name='مقالات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_article', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مقاله ذخیره شده',
                'verbose_name_plural': 'مقالات ذخیره شده',
                'ordering': ['-created'],
            },
        ),
    ]
