# Generated by Django 3.2 on 2021-05-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailArticleId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره آیدی')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'آیدی مقاله برای ارسال ایمیل',
                'verbose_name_plural': 'آیدی مقالات برای ارسال ایمیل',
            },
        ),
    ]
