# Generated by Django 3.2 on 2021-05-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_sendemailarticleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='send_email_article', to='article.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'مقاله برای ارسال ایمیل',
                'verbose_name_plural': 'مقالات برای ارسال ایمیل',
            },
        ),
        migrations.DeleteModel(
            name='SendEmailArticleId',
        ),
    ]
