# Generated by Django 3.2 on 2021-05-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_alter_sendemailarticle_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemailarticle',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='send_email_article', to='article.article', verbose_name='مقاله'),
        ),
    ]
