# Generated by Django 3.2 on 2021-05-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_alter_sendemailarticle_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendEmailArticle',
        ),
    ]
