# Generated by Django 3.2 on 2021-05-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_delete_sendemailarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='send_email',
            field=models.BooleanField(default=True, verbose_name='ارسال ایمیل'),
        ),
    ]
