# Generated by Django 3.2 on 2021-05-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
