# Generated by Django 3.2 on 2021-05-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='آدرس مقاله'),
        ),
    ]
