# Generated by Django 3.2 on 2021-05-08 15:10

from django.db import migrations, models
import site_settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgmaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_about_us', models.TextField(default='متن کوتاه درباره ما برای سایدبار', verbose_name='متن کوتاه درباره ما برای سایدبار')),
                ('instagram', models.CharField(blank=True, default='', max_length=120, verbose_name='آیدی اینستاگرام')),
                ('twitter', models.CharField(blank=True, default='', max_length=120, verbose_name='آیدی توییتر')),
                ('telegram', models.CharField(blank=True, default='', max_length=120, verbose_name='آیدی تلگرام')),
                ('youtube', models.CharField(blank=True, default='', max_length=120, verbose_name='آیدی یوتیوب')),
                ('site_logo', models.ImageField(upload_to=site_settings.models.upload_image_path, verbose_name='لوگوسایت')),
                ('site_icon', models.ImageField(upload_to=site_settings.models.upload_icon_image_path, verbose_name='آیکون سایت در هدر')),
            ],
            options={
                'verbose_name': 'تنظیم',
                'verbose_name_plural': 'تنظیمات',
                'ordering': ['-id'],
            },
        ),
    ]
